config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions'
  }

  namespace :admins do
    root 'manage_products#index'
    resources :manage_products
    resources :manage_orders, only:[:index, :edit, :update]
  end


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
  }

  devise_scope :user do
    get 'after_signup_confirmation', to: 'users/registrations#after_signup_confirmation'
  end

  resources :products, only:[:index, :show]

  scope :aftermails do
    get 'aftersignupmail', to:'aftermails#signup'
  end

  get 'cart', to: 'carts#index'
  patch 'cart', to: 'carts#update', as: 'update_cart_item_quantity'
  delete 'cart', to: 'carts#destroy', as: 'destroy_cart_item'
  post 'cart/added', to: 'carts#add_items'

  #  レジ
  resources :orders, only: [:new, :create]
  post 'orders/confirm', to: 'orders#confirm', as: 'orders_confirm'
  get 'orders/complete', to: 'orders#complete', as: 'orders_complete'

  # 注文履歴
  resources :histories, only: [:index, :show]

end

app/controllers/admins/manage_products_controller.rb
class Admins::ManageProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: %i[edit update destroy]

  layout 'admins'

  def index
    @products = Product.page(params[:page])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admins_manage_products_path, notice: "商品を１件登録しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to admins_manage_products_path, notice: "商品情報を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @product.destroy!
    redirect_to admins_manage_products_path, notice: "商品を１件削除しました"
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :image, :is_recommended)
  end
end

app/helpers/admins/manage_products_helper.rb
module Admins::ManageProductsHelper
end

app/views/admins/manage_products/edit.html.erb
<h1>商品編集</h1>
<hr>
<%= form_with model: @product, url: admins_manage_product_path ,method: :put do |f| %>

  <div class="custom-control custom-checkbox">
    <h4 class="ms-3 mb-3">
      <%= f.check_box :is_recommended, {class: "custom-control-input", id: "customCheck1"} %>
      <label class="custom-control-label" for="customCheck1">おすすめ</label>
    </h4>
  </div>

  <div class="row col-8 ms-0 mb-2">
    <h2 class="ps-0"><%= f.label :name, '商品名', class: 'form-label' %></h2>
    <%= f.text_field :name, class: 'form-control' %>
    <% if @product.errors.messages[:name].present? %>
      <strong class="text-danger">※ <%= @product.errors.full_messages_for(:name).first %></strong>
    <% end %>
  </div>

  <div class="row col-8 ms-0 mb-2">
    <h2 class="ps-0"><%= f.label :description, '商品説明', class: 'form-label' %></h2>
    <%= f.text_area :description, class: 'form-control', size: "20x5" %>
  </div>

  <div class="row col-4 ms-0 mb-2">
    <h2 class="ps-0"><%= f.label :price, '価格', class: 'form-label' %></h2>
    <%= f.number_field :price, class: 'form-control' %>
    <% if @product.errors.messages[:price].present? %>
      <strong class="text-danger">※ <%= @product.errors.full_messages_for(:price).first %></strong>
    <% end %>
  </div>

  <div class="row col-8 ms-0 mb-2">
    <h2 class="ps-0"><%= f.label :image, '画像', class: 'form-label' %></h2>
    <% if @product.image.attached? %>
      <p class="ps-0">登録されている画像</p>
      <%= image_tag @product.image, class: "img-fluid w-50 mb-3 ps-0"%>
    <% end %>

    <%= f.file_field :image, class: "form-control"%>
  </div>
  <hr>
  <%= f.submit "商品情報を更新", class:"btn btn-success" %>
<% end %>

app/views/admins/manage_products/index.html.erb
<h1>商品管理</h1>
<h2><%= link_to '+ 商品登録', new_admins_manage_product_path, class: 'btn btn-success ' %></h2>

<div class="table-responsive">
  <table class="table w-auto">
    <thead class="table-light text-center">
    <tr>
      <th scope="col">id</th>
      <th scope="col">編集</th>
      <th scope="col">削除</th>
      <th scope="col">おすすめ</th>
      <th scope="col">商品名</th>
    </tr>
    </thead>
    <tbody>
    <% @products.each do |product| %>
    <tr class="text-center">
      <th scope="row" class="align-middle"><%= product.id %></th>
      <td><%= link_to '編集', edit_admins_manage_product_path(product), class: "btn btn-primary"%></td>
      <td><%= link_to '削除', admins_manage_product_path(product), class: "btn btn-danger", method: :delete %></td>
      <td class="align-middle"><%= recommended_flag_to_mark(product) %></td>
      <td class="align-middle"><%= product.name %></td>
    </tr>
    <% end %>

    </tbody>
  </table>
  <%= paginate @products %>
</div>

app/views/admins/manage_products/new.html.erb
<h1>商品登録</h1>
<hr>
<%= form_with model: @product, url: admins_manage_products_path ,method: :post do |f| %>

  <div class="custom-control custom-checkbox">
    <h4 class="ms-3 mb-3">
      <%= f.check_box :is_recommended, {class: "custom-control-input", id: "customCheck1"} %>
      <label class="custom-control-label" for="customCheck1">おすすめ</label>
    </h4>
  </div>

  <div class="row col-8 ms-0 mb-2">
    <h2 class="ps-0"><%= f.label :name, '商品名', class: 'form-label' %></h2>
    <%= f.text_field :name, class: 'form-control' %>
    <% if @product.errors.messages[:name].present? %>
      <strong class="text-danger">※ <%= @product.errors.full_messages_for(:name).first %></strong>
    <% end %>
  </div>


  <div class="row col-8 ms-0 mb-2">
    <h2 class="ps-0"><%= f.label :description, '商品説明', class: 'form-label' %></h2>
    <%= f.text_area :description, class: 'form-control', size: "20x5" %>
  </div>

  <div class="row col-3 ms-0 mb-2">
    <h2 class="ps-0"><%= f.label :price, '価格', class: 'form-label' %></h2>
    <%= f.number_field :price, class: 'form-control' %>
    <% if @product.errors.messages[:price].present? %>
      <strong class="text-danger">※ <%= @product.errors.full_messages_for(:price).first %></strong>
    <% end %>
  </div>


  <div class="row col-8 ms-0 mb-2">
    <h2 class="ps-0"><%= f.label :image, '画像', class: 'form-label' %></h2>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <hr>
  <%= f.submit "商品を登録", class:"btn btn-success" %>
<% end %>