config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions'
  }

  namespace :admins do
    root 'manage_products#index'
    resources :manage_products
    resources :manage_orders, only:[:index, :edit, :update]
  end


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
  }

  devise_scope :user do
    get 'after_signup_confirmation', to: 'users/registrations#after_signup_confirmation'
  end

  resources :products, only:[:index, :show]

  scope :aftermails do
    get 'aftersignupmail', to:'aftermails#signup'
  end

  get 'cart', to: 'carts#index'
  patch 'cart', to: 'carts#update', as: 'update_cart_item_quantity'
  delete 'cart', to: 'carts#destroy', as: 'destroy_cart_item'
  post 'cart/added', to: 'carts#add_items'

  #  レジ
  resources :orders, only: [:new, :create]
  post 'orders/confirm', to: 'orders#confirm', as: 'orders_confirm'
  get 'orders/complete', to: 'orders#complete', as: 'orders_complete'

  # 注文履歴
  resources :histories, only: [:index, :show]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :delete_all
  has_many :products, through: :cart_items

  def calculate_total_price
    cart_total_price = 0
    cart_items.each do |cart_item|
      cart_total_price += cart_item.calculate_price
    end
    cart_total_price
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def calculate_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  validates :address_name, presence: true, length: { maximum: 30 }
  validates :zip, presence: true, length: { maximum: 7 }
  validates :address, presence: true, length: { maximum: 50 }
  validates :tel, presence: true

  def status_options
    ["注文受付", "支払い待ち", "発送準備", "発送完了"]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order

  def calculate_total
    quantity * ordered_price
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :cart_items, dependent: :delete_all
    has_many :carts, through: :cart_items
    has_one_attached :image

    validates :name, length: {maximum: 50}, presence: true
    validates :description, length: { maximum: 1000 }
    validates :price, numericality: {greater_than_or_equal_to: 0}

end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy

  scope :orders, -> {order('created_at DESC')}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable

  validates :name, presence: true, length: {maximum: 50}
  validates :email, length: { in: 6..254 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

end

app/controllers/admins/admin_controller.rb
class Admins::AdminController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins'

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :store_current_location, unless: :devise_controller?

  # どのビューやコントローラーでも呼び出せるメソッドとして定義する
  helper_method :current_cart

  private

  def store_current_location
    store_location_for(:user, request.url)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :setup_user_cart, only: [:index,:update, :destroy, :add_items]
  before_action :setup_this_cart_item!, only: [:add_items]

  def index
    @cart_items = @user_cart.cart_items
    @cart_total = @user_cart.calculate_total_price
  end

  def update
    this_cart_item = @user_cart.cart_items.find_by(product_id: params[:cart_item][:product_id])
    this_cart_item.update!(cart_item_params)
    redirect_to cart_path
  end

  def destroy
    @user_cart.cart_items.destroy(params[:cart_item])
    redirect_to cart_path
  end

  def add_items
    @product = Product.find(params[:id])
    if @this_cart_item.blank?
      @user_cart.cart_items.create(product_id: params[:id], quantity: params[:quantity].to_i)
    else
      @this_cart_item.quantity += params[:quantity].to_i
      @this_cart_item.save
    end

  end

  private
  def setup_user_cart
    if current_user.cart.blank?
      current_user.create_cart
    end
    @user_cart = current_user.cart
  end

  def setup_this_cart_item!
    @this_cart_item = @user_cart.cart_items.find_by(product_id: params[:id])
  end

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/completes_controller.rb
class CompletesController < ApplicationController
  def order
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_orders = current_user.orders.includes(:order_items).order('created_at DESC')
    @products = Product.all
  end

  def show
    @user_order = current_user.orders.find_by(params[:order_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.where(is_recommended: true).with_attached_image
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_cart, only: [:new, :confirm, :create]
  before_action :set_user_order, only: [:new]

  def new
    @bill = @user_cart.calculate_total_price
  end

  def confirm
    @order = current_user.orders.new(order_params)
    if @order.invalid?
      render action: :new
    end
  end

  def create
    @user_order = current_user.orders.create(order_params)

    @user_cart.products.each do |product|
      @order_item = @user_order.order_items.build
      @order_item.product_id = product.id
      @order_item.product_name = product.name
      @order_item.ordered_price = product.price
      @order_item.quantity = product.cart_items.find_by(product_id: product.id).quantity
      @order_item.save
    end

    @user_cart.destroy

    redirect_to orders_complete_path
  end

  def edit

  end

  def complete
  end

  private
  def set_user_cart
    @user_cart = current_user.cart
  end

  def set_user_order
    @order = current_user.orders.build
  end

  def order_params
    params.require(:order).permit(:address_name, :zip, :address, :tel, :paymethod, :bill)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page]).with_attached_image.per(16)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/users/mailer.rb
class Users::Mailer < Devise::Mailer
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end


  def after_sign_in_path_for(resource)
    stored_location_for(resource) || root_path
  end

end

app/helpers/admins/admin_helper.rb
module Admins::AdminHelper
end

app/helpers/admins/manage_orders_helper.rb
module Admins::ManageOrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def recommended_flag_to_mark(product)
    if product.is_recommended
      "●"
    else
      ""
    end
  end

end

app/views/carts/add_items.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h3 class="mt-3">以下の商品がカートに入りました</h3>
      <hr>
        <%= image_tag @product.image, class: "cart-image" %>

        <span class="ms-5"><%= @product.name %></span>
        <span class="ms-5">¥<%= @product.price %></span>
      <hr>
      <div class="text-center">
        <%= link_to '←商品一覧へ', products_path, class: "mb-2"  %>
        <%= link_to 'カートへ→',  cart_path, class: "ms-2"%>
      </div>

    </div>
  </div>
</div>

app/views/carts/index.html.erb
<div class="container">
  <h1>カートの中身</h1>
  <hr>
  <div class="row justify-content-center">
    <div class="col-md-9">
      <% @cart_items.each do |cart_item| %>
        <div class="row border p-3 mb-3 me-3">

          <div class="col-4">
            <%= image_tag cart_item.product.image, class: "w-75" %>
          </div>

          <div class="col-8">
            <div class="d-flex flex-column h-100">
              <%= link_to product_path(cart_item.product) do %>
                <h4><%= cart_item.product.name %></h4>
              <% end %>

              <div class="mb-auto">¥<%= number_with_delimiter cart_item.product.price %></div>

              <div>
                <%= form_with model: cart_item,url: update_cart_item_quantity_path, method: :patch, local: true do |f| %>
                  <%= f.hidden_field :product_id, value: cart_item.product.id %>
                  <span>個数:</span> <%= f.select :quantity,[*1..10], {},{class: "form-select w-25 d-inline"} %>
                  <%= f.submit '個数の変更', class: "btn btn-outline-secondary ms-1" %>
                <% end %>
              </div>

              <div class="mt-1">
                <%= link_to ' 削除', destroy_cart_item_path(cart_item: cart_item), class: "btn btn-danger", method: :delete %>
              </div>

            </div>
          </div>

        </div>
      <% end %>
    </div>

    <div class="col-md-3">
      <div class="border p-3 bg-light">
        <h4>商品合計</h4>
        <h4>¥<%= number_with_delimiter @cart_total %></h4>
        <%= link_to 'レジに進む', new_order_path, class: "btn btn-warning d-block mt-3" %>
      </div>

    </div>

  </div>
</div>

app/views/orders/complete.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 text-center">
      <h1>ご注文ありがとうございます</h1>

      <div class="d-grid gap-2 col-sm-4 mx-auto mt-3">
        <%= link_to '商品一覧へ', products_path, class: 'btn btn-lg btn-success' %>
      </div>

    </div>
  </div>
</div>

app/views/orders/confirm.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <h1>注文確認</h1>
      <hr class="mt-3">

        <div class="row">
          <div class="col-3">
            <h5 class="mb-4">１ お届け先</h5>
          </div>
          <div class="col-9">

            <div class="row col-8 ms-0 mb-2">
              <h6 class="ps-0"><%= @order.address_name %></h6>
            </div>

            <div class="row col-8 ms-0 mb-2">
              <h6 class="ps-0">〒 <%= @order.zip %></h6>
            </div>

            <div class="row col-8 ms-0 mb-2">
              <h6 class="ps-0"><%= @order.address %></h6>
            </div>

            <div class="row col-8 ms-0 mb-2">
              <h6 class="ps-0"><%= @order.tel %></h6>
            </div>

          </div>
          <hr class="mt-3">

          <div class="col-3">
            <h5 class="mb-4">２ お支払い方法</h5>
          </div>
          <div class="col-9">
            <%= @order.paymethod %>
          </div>
          <hr class="mt-3">

          <div class="col-3">
            <h5 class="mb-4">３ 注文商品</h5>
          </div>
          <div class="col-9 row">
            <div class="col-md-9">
              <% @user_cart.cart_items.each do |cart_item| %>
                <div class="row border p-3 mb-3 me-3">

                  <div class="col-4">
                    <%= image_tag cart_item.product.image, class: "w-75" %>
                  </div>

                  <div class="col-8">
                    <div class="d-flex flex-column h-100">
                      <h4><%= cart_item.product.name %></h4>
                      <div class="mb-auto">¥<%= cart_item.product.price %></div>
                      <div class="mb-auto">数量: <%= cart_item.quantity %></div>
                    </div>
                  </div>

                </div>
              <% end %>
            </div>
          </div>
          <hr class="mt-3">

          <div class="col-3 d-flex align-items-center">

              <%= form_with model: @order , method: :post, class: "w-100", local: true do |f| %>
                <%= f.hidden_field :address_name %>
                <%= f.hidden_field :address %>
                <%= f.hidden_field :zip %>
                <%= f.hidden_field :tel %>
                <%= f.hidden_field :paymethod %>
                <%= f.hidden_field :bill %>
                <%= f.submit '注文を確定', class: "btn btn-warning d-block w-100" %>
              <% end %>

          </div>

          <div class="col-9 d-flex align-items-center">
            <h5 class="m-0">請求額:  ¥<%= number_with_delimiter @order.bill %></h5>
          </div>

          <div class="row justify-content-center">

          </div>

        </div>




    </div>
  </div>
</div>

app/views/orders/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <h1>注文設定</h1>
      <hr class="mt-3">
      <%= form_with model: @order, url: orders_confirm_path, local: true do |f| %>
        <div class="row">
          <div class="col-3">
            <h5 class="mb-4">１ お届け先</h5>
          </div>

          <div class="col-9">
            <div class="col-8 ms-0 mb-2">
              <h6 class="ps-0"><%= f.label :address_name, 'お届け先氏名・組織名', class: 'form-label' %></h6>
              <%= f.text_field :address_name, class: 'form-control w-50' %>
              <% if @order.errors.messages[:address_name].present? %>
                <strong class="text-danger">※ <%= @order.errors.full_messages_for(:address_name).first %></strong>
              <% end %>
            </div>

            <div class="col-8 ms-0 mb-2">
              <h6 class="ps-0"><%= f.label :zip, '郵便番号', class: 'form-label' %></h6>
              <%= f.text_field :zip, class: 'form-control w-50' %>
              <% if @order.errors.messages[:zip].present? %>
                <strong class="text-danger">※ <%= @order.errors.full_messages_for(:zip).first %></strong>
              <% end %>
            </div>

            <div class="col-8 ms-0 mb-2">
              <h6 class="ps-0"><%= f.label :address, 'お届け先住所', class: 'form-label' %></h6>
              <%= f.text_field :address, class: 'form-control' %>
              <% if @order.errors.messages[:address].present? %>
                <strong class="text-danger">※ <%= @order.errors.full_messages_for(:address).first %></strong>
              <% end %>
            </div>

            <div class="col-8 ms-0 mb-2">
              <h6 class="ps-0"><%= f.label :tel, 'ご連絡先', class: 'form-label' %></h6>
              <%= f.text_field :tel, class: 'form-control w-50' %>
              <% if @order.errors.messages[:tel].present? %>
                <strong class="text-danger">※ <%= @order.errors.full_messages_for(:tel).first %></strong>
              <% end %>
            </div>

          </div>
        </div>

        <div class="row mt-5">
          <div class="col-3">
            <h5 class="mb-4">２ お支払い方法</h5>
          </div>

          <div class="col-9">
            <div class="col-8 ms-0 mb-2">
              <%= f.select :paymethod, ['代引','銀行振込','クレジット'],{},{class: "form-control w-auto"} %>
            </div>
          </div>
        </div>

          <hr class="mt-3">

          <div class="row justify-content-center">
            <%= f.hidden_field :bill, value: @bill %>
            <%= f.submit '注文確認画面へ', class: "btn btn-warning d-block mt-3 w-50" %>
          </div>

        </div>


      <% end %>

    </div>
  </div>
</div>