config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions'
  }

  namespace :admins do
    root 'manage_products#index'
    resources :manage_products
    resources :manage_orders, only:[:index, :edit, :update]
  end


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
  }

  devise_scope :user do
    get 'after_signup_confirmation', to: 'users/registrations#after_signup_confirmation'
  end

  resources :products, only:[:index, :show]

  scope :aftermails do
    get 'aftersignupmail', to:'aftermails#signup'
  end

  get 'cart', to: 'carts#index'
  patch 'cart', to: 'carts#update', as: 'update_cart_item_quantity'
  delete 'cart', to: 'carts#destroy', as: 'destroy_cart_item'
  post 'cart/added', to: 'carts#add_items'

  #  レジ
  resources :orders, only: [:new, :create]
  post 'orders/confirm', to: 'orders#confirm', as: 'orders_confirm'
  get 'orders/complete', to: 'orders#complete', as: 'orders_complete'

  # 注文履歴
  resources :histories, only: [:index, :show]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :delete_all
  has_many :products, through: :cart_items

  def calculate_total_price
    cart_total_price = 0
    cart_items.each do |cart_item|
      cart_total_price += cart_item.calculate_price
    end
    cart_total_price
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def calculate_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  validates :address_name, presence: true, length: { maximum: 30 }
  validates :zip, presence: true, length: { maximum: 7 }
  validates :address, presence: true, length: { maximum: 50 }
  validates :tel, presence: true

  def status_options
    ["注文受付", "支払い待ち", "発送準備", "発送完了"]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order

  def calculate_total
    quantity * ordered_price
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :cart_items, dependent: :delete_all
    has_many :carts, through: :cart_items
    has_one_attached :image

    validates :name, length: {maximum: 50}, presence: true
    validates :description, length: { maximum: 1000 }
    validates :price, numericality: {greater_than_or_equal_to: 0}

end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy

  scope :orders, -> {order('created_at DESC')}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable

  validates :name, presence: true, length: {maximum: 50}
  validates :email, length: { in: 6..254 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

end

app/controllers/admins/admin_controller.rb
class Admins::AdminController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins'

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :store_current_location, unless: :devise_controller?

  # どのビューやコントローラーでも呼び出せるメソッドとして定義する
  helper_method :current_cart

  private

  def store_current_location
    store_location_for(:user, request.url)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :setup_user_cart, only: [:index,:update, :destroy, :add_items]
  before_action :setup_this_cart_item!, only: [:add_items]

  def index
    @cart_items = @user_cart.cart_items
    @cart_total = @user_cart.calculate_total_price
  end

  def update
    this_cart_item = @user_cart.cart_items.find_by(product_id: params[:cart_item][:product_id])
    this_cart_item.update!(cart_item_params)
    redirect_to cart_path
  end

  def destroy
    @user_cart.cart_items.destroy(params[:cart_item])
    redirect_to cart_path
  end

  def add_items
    @product = Product.find(params[:id])
    if @this_cart_item.blank?
      @user_cart.cart_items.create(product_id: params[:id], quantity: params[:quantity].to_i)
    else
      @this_cart_item.quantity += params[:quantity].to_i
      @this_cart_item.save
    end

  end

  private
  def setup_user_cart
    if current_user.cart.blank?
      current_user.create_cart
    end
    @user_cart = current_user.cart
  end

  def setup_this_cart_item!
    @this_cart_item = @user_cart.cart_items.find_by(product_id: params[:id])
  end

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/completes_controller.rb
class CompletesController < ApplicationController
  def order
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_orders = current_user.orders.includes(:order_items).order('created_at DESC')
    @products = Product.all
  end

  def show
    @user_order = current_user.orders.find_by(params[:order_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.where(is_recommended: true).with_attached_image
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_cart, only: [:new, :confirm, :create]
  before_action :set_user_order, only: [:new]

  def new
    @bill = @user_cart.calculate_total_price
  end

  def confirm
    @order = current_user.orders.new(order_params)
    if @order.invalid?
      render action: :new
    end
  end

  def create
    @user_order = current_user.orders.create(order_params)

    @user_cart.products.each do |product|
      @order_item = @user_order.order_items.build
      @order_item.product_id = product.id
      @order_item.product_name = product.name
      @order_item.ordered_price = product.price
      @order_item.quantity = product.cart_items.find_by(product_id: product.id).quantity
      @order_item.save
    end

    @user_cart.destroy

    redirect_to orders_complete_path
  end

  def edit

  end

  def complete
  end

  private
  def set_user_cart
    @user_cart = current_user.cart
  end

  def set_user_order
    @order = current_user.orders.build
  end

  def order_params
    params.require(:order).permit(:address_name, :zip, :address, :tel, :paymethod, :bill)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page]).with_attached_image.per(16)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/users/mailer.rb
class Users::Mailer < Devise::Mailer
end

app/helpers/admins/admin_helper.rb
module Admins::AdminHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def recommended_flag_to_mark(product)
    if product.is_recommended
      "●"
    else
      ""
    end
  end

end

app/views/aftermails/signup.html.erb
サインアップ認証メール後のview

app/views/layouts/_ad_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

      <a class="navbar-brand" href="/">Rails-demo2</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav mb-2 mb-lg-0">
          <li class="nav-item mx-2">
            <% if admin_signed_in? %>
              <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link active' %>
            <% end %>
          </li>
        </ul>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/_ad_sidebar.html.erb
<div class="container ml-3">
  <h2>商品管理</h2>
  <%= link_to '商品一覧', admins_manage_products_path %>

  <h2 class="mt-4">注文管理</h2>
  <%= link_to '注文一覧', admins_manage_orders_path %>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Rails-demo2</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav mb-2 mb-lg-0">
          <li class="nav-item"><%= link_to '管理画面', admins_root_path, class: "nav-link active" %></li>
          <% if user_signed_in? %>

            <div class="dropdown">
              <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                会員メニュー
              </a>

              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <%= link_to '注文履歴', histories_path, class: "dropdown-item" %>
                <%= link_to 'ログアウト', destroy_user_session_path, class: "dropdown-item", method: :delete %>
              </div>
            </div>

          <% else %>
            <li class="nav-item mx-2">
              <%= link_to 'ログイン', new_user_session_path, class: "nav-link active" %>
            </li>
          <% end %>


          <li class="nav-item mx-2">
            <%= link_to 'カート', cart_path, class: "nav-link active" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails-demo2</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render partial: 'layouts/ad_header' %>

  <% if flash.notice %>
    <div class="alert alert-success text-center"><%= notice %></div>
  <% elsif flash.alert %>
    <div class="alert alert-danger text-center"><%= alert %></div>
  <% end %>
  <div class="row mb-5">
    <div class="col-3 mt-3">
     <%= render partial: 'layouts/ad_sidebar' %>
    </div>
    <div class="col-8 mt-3">
      <main>
        <%= yield %>
      </main>
    </div>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails-demo2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>

    <% if flash.notice %>
      <div class="alert alert-success text-center"><%= notice %></div>
    <% elsif flash.alert %>
      <div class="alert alert-danger text-center"><%= alert %></div>
    <% end %>

    <main class="my-5">
      <%= yield %>
    </main>

  </body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsEc2</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render partial: 'layouts/ad_header' %>

  <div class="row mb-5">
    <main>
      <%= yield %>
    </main>
  </div>

</body>
</html>